### ISSUE TITLE
Font issue in Firefox - ampersand ("&") doesn't display properly

### ISSUE THREAD

**Issue by Tykzz** [gskinner/regexr#116]
![ampersand_in_firefox](https://cloud.githubusercontent.com/assets/9462146/10879274/54c50b42-8153-11e5-95b5-cb05416979e3.jpg)

It works properly in Chrome and Opera. Also when I change the font in Firefox. 
I use Windows if that matters.

**Comment by Nightfirecat** [comment]
I'm running Firefox 41.0.1 (not quite latest), and I'm not seeing the same behavior...

![substitution menu from regexr](http://i.imgur.com/px7RTTg.png)

**Comment by wdamien** [comment]
@Tykzz do you have the Cabin font installed on your system? I've seen this before and it was because of a corrupt font installed on the users system. If you do have Cabin installed, can you try reinstalling it, and restarting FF?  https://www.google.com/fonts/specimen/Cabin, hopefully that will resolve the issue.

**Comment by Tykzz** [comment]
@wdamien I don't have Cabin but I had Source Code Pro font. Apparently it was corrupt because everything works well after I uninstalled it. Thanks for your lead.
