### ISSUE TITLE
^[0-9]

### ISSUE THREAD

**Issue by jbruns2015** [gskinner/regexr#138]
Trying to simply use ^[0-9] as a pattern on the default web site (http://www.regexr.com/) and it says no match.

I feel stupid that I am doing something wrong.

Why does ^[0-9] not match on anything but [0-9] does?

**Comment by wdamien** [comment]
This is expected behavior since `^` matches from the beginning of the string. Quoted from the RegExr docs:

> ^ Matches the beginning of the string, or the beginning of a line if the multiline flag (/m) is enabled. This matches a position, not a character.

So whats happening is`^[0-9]` is trying to find a match from the beginning of the string, not finding a number at position 0, and stopping (put a number at the first character, and you'll see what I mean). Where as `[0-9]` searches until it finds a match.  If you add `/m` to `^[0-9]`it will find some results.

Fyi, usually Stackoverflow is a better place for Regex questions like this, we like to keep this area for just issues. Thanks!

**Comment by jbruns2015** [comment]
Do these not start with a number?

[cid:image001.png@01D164B5.21290690]

Regards,
Joe Bruns

**Comment by wdamien** [comment]
I'm not seeing an image, but I think your referring to these lines:

```
0123456789 _+-.,!@#$%^&*();\/|<>"'
12345 -98.7 3.141 .6180 9,000 +42
555.123.4567	+1-(800)-555-2468
```

`^[0-9]` will match `0,1,5` but only if the `/m` flag is enabled.  `^` is telling RegEx to start searching from the beginning of the entire string, when it doesn't find a match, it stops.  You can see this with the default RegExr text by using this expression `^[A-Z]`, it will match `W`, then stop looking for matches.

Hopefully that helps!
