### ISSUE TITLE
Shared links don't load the correct text when opened in an unfocused window.

### ISSUE THREAD

**Issue by tehvgg** [gskinner/regexr#149]
If a shared link is opened in a new tab, or you click away from the tab immediately after opening, the **Text** field is populated with the default copy and not the copy connected to the shared expression. However, the **Expression** field and **Replace** or **List** Tools are populated correctly.

Also, the expression ID is removed from the URL.

http://regexr.com/3da63

Open that link in this window.
Back up, open it again but this time in a new tab. Give it a couple seconds to load, open the tab.
The "Text" field will be incorrect the second time.

OS: Windows 10
Browsers: Chrome 50.0.2661.87, Firefox 40.0

**Comment by tehvgg** [comment]
The new tab has a history event created prior to the page you can see. When navigating back to it, you get the properly loaded text and expression ID in the url. Seems that the new tab calls one `BrowserHistory.go()` from one of these two lines

* https://github.com/gskinner/regexr/blob/dea039af1403d1782fa343b997d88497fb3deafc/js/index.template.js#L149
* https://github.com/gskinner/regexr/blob/dea039af1403d1782fa343b997d88497fb3deafc/js/views/DocView.js#L565

**Comment by gskinner** [comment]
Will test this specifically for v3.0. Hopefully will be solved, since all of this is largely rewritten.

**Comment by gskinner** [comment]
@tehvgg Can you test this against v3 and close if resolved?

**Comment by Nightfirecat** [comment]
Is v3 live in any way? regexr.com still displays v2.1, and regexr.com/v3 redirects to the first link.

In any case, I tested on regexr.com using the original comment's link, and noticed the same behavior [in this comment on #203](https://github.com/gskinner/regexr/issues/203#issuecomment-347248967) ([my link](https://regexr.com/3h91u), for convenience)

In both cases, the issue is still present; if you open the link in a new tab (middle-mouse or ctrl+click) and only focus it after it loads, the text is the default "Welcome to RegExr v2.1..." rather than the text used in the saved pattern.

**Comment by gskinner** [comment]
Sorry - it should be in the next hour, just doing a final test pass. @tehvgg is internal and has access to the beta. :)

**Comment by tehvgg** [comment]
Could not reproduce in v3.
