### ISSUE TITLE
$ anchor seems to not be working

### ISSUE THREAD

**Issue by KhainTCore** [gskinner/regexr#160]
Hello,

I was using the $ anchor to test for file extensions, but it seems to simply break when I add the $ anchor to the regex.
Ex. 
exp: (.csv)$
testText: import.csv
              import.csv.exe

Should only match the first, but it matches neither.
I tested the same expression in some javascript to make sure I wasn't going crazy. It works fine there with the .matches() function.

**Comment by Nightfirecat** [comment]
When your input spans multiple lines and you use a beginning- or end-of-string anchor, the string will not match correctly unless the match is at the end of the full string, rather than at the end of the line. [(example)](http://regexr.com/3e4qu)

To make the regex work correctly, you must add the multiline flag, making the regex become `/(.csv)$/m`. [(example)](http://regexr.com/3e4r1)

**Comment by KhainTCore** [comment]
Well, I thought I had tried that. I should have made a better test case.
Thank you for the quick response, and the detailed examples. Sorry for taking up your time.

**Comment by Nightfirecat** [comment]
Not a problem, glad to help!
