### ISSUE TITLE
Phone regexp example rejects Belarussian numbers

### ISSUE THREAD

**Issue by kirillDanshin** [gskinner/regexr#180]
To test:
```
+375291234567
375291234567
80291234567
291234567
0291234567
```

**Comment by Nightfirecat** [comment]
From the description of the phone number regex:

> North American phone number matching. Highly simplified!

**Comment by Nightfirecat** [comment]
Anyways, as it turns out, [processing phone numbers is complicated](https://github.com/googlei18n/libphonenumber/blob/master/FALSEHOODS.md), probably enough so that you should either:

a) Consider not verifying user input&mdash;expect that they will provide a correctly-formatted version of their phone number
b) Use [a dedicated library for parsing phone numbers](https://github.com/googlei18n/libphonenumber)

**Comment by lannymcnie** [comment]
Closing this out. This issue list is for reporting problems or suggestions for the RegExr tool and website, and not discussing specific library examples.
