### ISSUE TITLE
Add transformation possibilities to "Replace" tool

### ISSUE THREAD

**Issue by AlexGustafsson** [gskinner/regexr#183]
The tool could offer several operators for transforming text in the "Replace" tool.

For example, let's say we have the matches `"hello"`, `"there"` and `"gskinner"` indexed 1 through 3. As expected, if I were to type `"$1 $2, $3"` I would end up with the string `"hello there, gskinner"`. What I would like is the ability to for example capitalize a match, or capitalize the first character so that I could write something like `"$^1 $2, $3"` to produce `"Hello there, gskinner"`.

I've got some time to take a look at this this week. Would this feature be welcome? If so, what operators should exist and how should they work?

**Comment by Nightfirecat** [comment]
Not that this feature wouldn't be appreciated for some, but that's not a standard regex feature. Just my 2¢.

**Comment by AlexGustafsson** [comment]
I figured. I just wasn't sure "how true to the original" this tool aimed to be.

**Comment by gskinner** [comment]
It's definitely interesting, but we do try hard to only surface features that exist in the language. I guess the closest thing to an exception to this is the List feature. It doesn't directly reflect a feature of RegExr, but it was so insanely useful I couldn't help adding it.

I could possibly see something like this living under it's own tab, but it would take a bit of work to flesh out the value, and how it would be surfaced to the user, since you're proposing custom syntax that wouldn't "belong" in the Reference.
