### ISSUE TITLE
Anchors don't work

### ISSUE THREAD

**Issue by dwrz** [gskinner/regexr#186]
Anchors don't seem to be working for me. They work on this site: http://scriptular.com/, but not regexr.

I'm trying to run this expression:
^1?\s?(\(?\d{3}\)?)(\s|-)?(\d{3})(\s|-)?(\d{4})$

I get no matches for these strings:
555-555-5555
(555)555-5555
(555) 555-5555

Even though they match on scriptular.

Not sure if it matters, but I'm on Linux + Chromium.

**Comment by gskinner** [comment]
I think using the multiline (m) flag should do what you need. From the docs:

When the multiline flag is enabled, beginning and end anchors (^ and $) will match the start and end of a line, instead of the start and end of the whole string.
Note that patterns such as /^[\s\S]+$/m may return matches that span multiple lines because the anchors will match the start/end of any line.
