### ISSUE TITLE
Ability to delete saved expressions in v3

### ISSUE THREAD

**Issue by h1nk** [gskinner/regexr#221]
Is there anyway to delete saved expressions in v3? I see that you can edit the title and tags etc. but no way to remove an expression from your saved list. I can imagine my saved list will get quite cluttered eventually.

**Comment by gskinner** [comment]
Not yet, but we will likely add this soon. We will also be adding search to My Patterns, so you can quickly filter through old patterns.

**Comment by anothernode** [comment]
> I see that you can edit the title and tags etc. but no way to remove an expression from your saved list.

I can't even figure out how to edit the title, description or anything. Is that really possible? How?

**Comment by gskinner** [comment]
This is in v3.3, and we'll continue looking at how to surface it more clearly.

**Comment by gskinner** [comment]
Editing / deleting is via the save / share panel.

**Comment by anothernode** [comment]
Oh my god, I finally figured out how to do it. In case someone as slow-witted as me finds this:

1. You gotta first go to "My Patterns" and select the pattern you want to delete
2. Then, and this is crucial, click the URL displayed under the pattern title
3. Then go back to the main menu and choose "Save & Share"
4. And then, you'll have a "Delete" button at the bottom of the side menu

The "Delete" button is only available if you followed all the steps as described.

This feels like a bit of a cumbersome process for such a basic task, especially because the rest of the UX is so slick and well designed.

**Comment by gskinner** [comment]
It's definitely more complex than we'd like. I'm very open to ideas on how to improve the workflow. For example, one small change we've been debating is having the "Save/Share" panel open whenever you load a pattern (by clicking the URL or double clicking in the list).

The pro is that it will surface the pattern info and options. The con is that it doesn't work well if you're going through a bunch of patterns and loading them to test one at a time.

**Comment by anothernode** [comment]
I think for me personally the most crucial cognitive disconnect was that after choosing a pattern in the _My Patterns_ submenu, I had to click that _regexr.com/xyz_ URL in order to actually load the pattern. For me, that's just not intuitive. If you could add a label to that field saying "Load" or something like that, that would have definitely helped me to figure this out quicker. Maybe that's just me, but it's also low hanging fruit, I guess.

Beyond that I wonder if the whole _Save & Share_ submenu is needed altogether. I mean, maybe there is some technical reason for having it, but from a purely UX perspective I would tend to think that all of it's functionality could be moved directly into the _My patterns_ submenu, just like it's already the case with the "Favorite" button. For example, there could be a little Trash icon next to the heart icon for every pattern listed in the _My patterns_ submenu.

**Comment by anothernode** [comment]
- I obviously like the "Load" label 😉
- I also like the idea of putting an icon to the top bar and the pattern title bar. Although, maybe it's just me, but I would expect that cog icon to lead to me to some general application preferences page. Maybe one of these options or something similar would be more appropriate?
  - https://fontawesome.com/icons/share?style=solid
  - https://fontawesome.com/icons/share-square?style=solid
  - https://fontawesome.com/icons/share-square?style=regular
  - https://fontawesome.com/icons/share-alt-square?style=solid
  - https://fontawesome.com/icons/share-alt?style=solid
  - https://fontawesome.com/icons/save?style=solid
  - https://fontawesome.com/icons/save?style=regular
- To me, the pattern title bar doesn't feel cluttered, even with the rating buttons, but it certainly doesn't do harm either to move them to their own row...

**Comment by gcjuan** [comment]
Hi @gskinner  ! =)

I have found this closed issue but I'm still not able to delete some own patterns.

I created one pattern and suddenly (I don't really know how nor why), a couple of forks were added to the list of "My Patterns" in addition to the one I created.

I tried to delete the one I created successfully but when trying to delete the forks a warning sign with an error on a pop-up is shown (see screenshot). The error says: 'no docs for error = "undefined" '.
The same behavior happens if I try to rename a fork. It seems like if they weren't storaged on the DDBB.

Have you perhaps some hint/solution here?

Thanks in advance :wink: 
![imagen](https://user-images.githubusercontent.com/19599325/60761924-af94b900-a053-11e9-882a-08221093fae4.png)
