### ISSUE TITLE
Request: Comments

### ISSUE THREAD

**Issue by tomhumphrey** [gskinner/regexr#231]
Would it be possible to be able to add comments (i.e. lines that aren't interpreted by RegEx) in the text box?

**Comment by Nightfirecat** [comment]
You already can. This regex shows a comment being used (only in PCRE-flavored regex; Javascript does not support it): `/([A-Z])(?#this is a comment)\w+/g`

https://regexr.com/3hmqo

**Comment by gskinner** [comment]
I think @tomhumphrey is asking for this in Text. So you could have a pattern like:
`/^.+/gm`
And then have lines with text that it doesn't match on.

I can see how that would be helpful, but it's very problematic to implement in a tool like this, since it requires us to pick an arbitrary comment escape, which might then be needed in a match by someone.

It would also require us to step away from allowing the regex engine to do the work in an unadulterated fashion, and instead have us slicing up the Text input and preprocessing it.

I think I'm going to close this one for now. If we ever consider preprocessing text input (ex. treating lines as completely distinct strings), I might revisit this.

Additional input is welcome.

**Comment by tomhumphrey** [comment]
@gskinner That's exactly what I meant. I can understand this being a very difficult task to achieve to avoid the regexr interpreting it. But, would be a nice to have - especially when sharing regexr saves.
Thanks for the response and keep up the good work - This is one of my favourite online tools :+1:
