### ISSUE TITLE
Save doesn't save the replace RegEx

### ISSUE THREAD

**Issue by TomHashNL** [gskinner/regexr#257]
Was a bit disappointed my replace RegEx was gone after I saved my RegEx.
Not sure if it should save it, ah well...

Super nice tool anyway!

**Comment by wdamien** [comment]
Thanks for the issue report! I was able to track down and fix a bug that was causing replace not to save correctly.  It turns out handling of certain hidden characters was not correct. Saving with any of these characters; \n \t \r  would cause replace / list values to return null.  Its pushed live to regexr.com.

If you can still reproduce replace not saving with the latest version, please re-open this issue with some more details. If not, Happy RegExing!
