### ISSUE TITLE
expression bug 

### ISSUE THREAD

**Issue by Carlos19952000** [gskinner/regexr#266]
((2|4|6|8)|[1-9]+(0|2|4|6|8)+)+

This expression don't working, the pairs numbers following by zero, for example 40, 60, 80 etc are validates by the OR of the second expression admit only the firts part behind of OR.
Thanks

**Comment by gskinner** [comment]
Hi Carlos,

This isn't a forum for help with Regular Expressions. I'd suggest asking this on Stack Overflow. Please only post bugs / feature requests for RegExr here.

Thanks!

**Comment by Carlos19952000** [comment]
Hi gskinner

it's a bug, because the expression is correct and should validate this data but doesn't recognize. look the capture please

![image](https://user-images.githubusercontent.com/33904996/41172459-89b630ee-6b19-11e8-96d1-1325a2ba2717.png)

**Comment by gskinner** [comment]
Those matches are correct. We are executing matching in real Regular Expression engines for the target platform (for Javascript, that's your browser), so we can't have match errors per se.

That said, I'll help you with this pattern:

Look at `20` as the input value.

It begins the match looking at the first character `2`. It is able to satisfy the first option `(2|4|6|8)`, so it moves on to the second character `0`. This character does not satisfy any part of a match, so it returns the found match `2`.

Now, if you swap the order of your alternation statement, then it will work as you expect, because it will the first option it tries will be the one that matches `20`.

`([1-9]+(0|2|4|6|8)+|(2|4|6|8))+`
