### ISSUE TITLE
capture group empty

### ISSUE THREAD

**Issue by embradded** [gskinner/regexr#280]
REGEX: ^(trace|t)(\s(((malloc|m)|(calloc|c))))*

INPUT: trace malloc calloc

BUG: Group 5 is empty when it should be "malloc"

![image](https://user-images.githubusercontent.com/6445922/44498275-bcc2d800-a63a-11e8-82b3-5f9fbe94c936.png)

**Comment by gskinner** [comment]
This is the correct output. You can test it with:

`/^(trace|t)(\s(((malloc|m)|(calloc|c))))*/g.exec("trace malloc calloc")`

outputs:

`["trace malloc calloc", "trace", " calloc", "calloc", "calloc", undefined, "calloc"]`

That's because Group 5 is redefined each time it repeats the match on group 2. As such, in the last repeat (the only one that is returned) it is empty.
