### ISSUE TITLE
Regex misses match if next character is end of line, but works if it is a whitespace.

### ISSUE THREAD

**Issue by ruffianeo** [gskinner/regexr#342]
/[+-]{0,1}[0-9]+(.[0-9]*){1}/g 
for input:
```
0 -1 +1
+0.0001 -42.343.3434
-2
+3 
- + 
*foo *rab *ofo *bar *foo
```
the +1 and the -2 (first and 3rd line) should be matched and highlighted. But they are not.
+3 has a space behind it and then end of line and it is matched.
+1 and +2 have no blank and are not matched.

**Comment by Nightfirecat** [comment]
They are not matched because there is no way for the regex to match:

1. A `+` or `-` sign
2. One or more digits
3. Any **non-newline character** followed by zero or more digits

The first two points above would capture `+1` or `-2`, but the third point cannot be satisfied.

**Comment by ruffianeo** [comment]
So why does adding a blank after +1 change this? I know the regex is not what I intended. But something IS fishy here. 0 and -1 are recognized (highlighted) but +2 is not - and adding that blank changes this. This makes no sense to me.

**Comment by gskinner** [comment]
`(.[0-9]*)`
The `.` (dot) in this part of your expression matches any character except for a newline. It is a required token in your expression. Thus `+3 ` matches (a space is not a newline), but `+3` at the end of a line won't match, because there is no non-newline character for it to match.

RegExr includes an "Explain" tool, which makes debugging these kinds of things pretty straightforward. Similarly, you can mouse over the individual tokens in the Expression to get an explanation of what each one does. Happy RegExing!
