### ISSUE TITLE
Number of matches its always "No match"

### ISSUE THREAD

**Issue by EmanuelMoreira** [gskinner/regexr#351]
The number of matches label in the upper-right corner always display the "No match" value instead of the correct number of matches (see image below).
![image](https://user-images.githubusercontent.com/47996512/78022404-c51de180-734c-11ea-9ff8-aac11dda5535.png)

**Comment by gskinner** [comment]
Are you on Safari perchance? It appears that Safari is _aggressively_ caching something. Try clearing your cache and it should work fine.

I'm a little stumped by it, since we actually rename our JS / CSS files entirely between versions now, and the "Tests" button wouldn't even show up if the html was cached. Doesn't help that I can no longer easily repro, since I cleared my cache.

Could you check the developer console and copy/paste any errors you see? It may help narrow down what's happening. Thanks!

**Comment by EmanuelMoreira** [comment]
It was the cache. I tried before to clean it, but now it solved the error.
For reference I was using Chrome.
Thanks for the help.
