### ISSUE TITLE
Save Tests with Pattern.

### ISSUE THREAD

**Issue by rafegoldberg** [gskinner/regexr#355]
**In short**: save and restore functionality should be extended to the new Tests feature!

---

<img align=right src=https://user-images.githubusercontent.com/886627/80611139-145c3e00-89ef-11ea-9fee-b360299f868f.png width=303.5> Logged in users can store Patterns in a library of sorts, which also saves the associated contents of the Text panel. This content can be restored later, alongside the regex pattern itself, which is fantastic for sharing quick demos and for editing patterns. When you save or restore a pattern, it should also include the entire Test suite as well!

**Comment by gskinner** [comment]
Just to make sure we're on the same page:
Save and restore works for test suites (let me know if you've seen otherwise), however, tests are currently not included in the preview for the pattern, and can't be loaded separately from the rest of the pattern.

Would a simple approach work? Ex. just adding a third section that said something like: "12 Tests" with the load arrow icon?

**Comment by gskinner** [comment]
Maybe something like this?
![image](https://user-images.githubusercontent.com/157128/80616719-78d2c980-89fe-11ea-99b7-e626399fe216.png)

**Comment by rafegoldberg** [comment]
@gskinner lol, wow. I just double checked and see now that you are _entirely_ right. Works like a charm! Whoops... And yeah—it'd be great to list those Tests in the Saved Pattern panel too! That ought to be enough to save you from dummies like myself getting confused and opening redundant issues in this (fantastic) repo before thoroughly testing said functionality.

Closing this issue; thanks!

**Comment by rafegoldberg** [comment]
Also, I've been using RegExr for something like six years now (holy jesus, time...) It's an absolutely amazing tool and learning resource; pretty much how I learned regex! That is to say, I really appreciate all the work that you've put in to it!

**Comment by gskinner** [comment]
Thanks for the feedback! I've been building RegExr (as free time permits) for _yikes_ 12 years now, and it's always been a labor of love. At first it was just an excuse for me to learn RegEx, but it's evolved into a tool that helps thousands of people every day. It's come a long way since v0.1:

https://blog.gskinner.com/archives/2008/03/regexr_free_onl.html

Fun times! :)
