### ISSUE TITLE
Global search 'g' flag doesn't work in Tests

### ISSUE THREAD

**Issue by aniket-tyagi-ru** [gskinner/regexr#381]
Adding the global flag for expressions works in 'Text' section but not in 'Tests' section.

![image](https://user-images.githubusercontent.com/42098237/92128382-40068f00-edfa-11ea-88e5-e98ada9c1741.png)

![image](https://user-images.githubusercontent.com/42098237/92128321-30874600-edfa-11ea-9f19-eeee250d9423.png)

**Comment by matthew-ia** [comment]
I'm having the same or a similar issue. 

@aniket-tyagi-ru I see your Test is a little different from mine though; you have selected "Match Full", which causes the failure in your specific test, I think. (That result may still be a bug, though).

My issue occurs with "Match Any". Technically, the Test passes, but I'd expect it to highlight all instances of the match as it does in Text. Perhaps the exiting behavior is intended since it "Match[es] Any" (the first instance) and then reports the test passing. Maybe the solution for my specific issue would be to have a "Match All" option to highlight/indicate all the match occurrences. 

**Tests (Does Not Work):**
![Screen Shot 2022-08-19 at 10 45 26 PM](https://user-images.githubusercontent.com/17885141/185726166-4b33520b-fe89-449c-8286-7774a9038059.png)

**Text (Works):**
![Screen Shot 2022-08-19 at 10 45 15 PM](https://user-images.githubusercontent.com/17885141/185726164-5d67c025-731f-4893-9737-556e1c1439b4.png)

**Comment by myverdict** [comment]
I am facing the same issue. I have created an issue: 

https://github.com/gskinner/regexr/issues/513

I hope this get fixed, since I see this problem seems to be existing at least since September 2020.

**Comment by gskinner** [comment]
This is expected behaviour. The test is to "match any", so as soon as a match is found, the test is successful. It's optimized to not waste additional resources to find further matches because the pass/fail is already determined.
