### ISSUE TITLE
End character won't match in Browser version

### ISSUE THREAD

**Issue by parsa-ra** [gskinner/regexr#421]
I tried the `\w+$` expression with multiple regular expression engines against the same string (formatted copy) but I think this implementation not matching end characters at all, am I missing something? checkout the following screenshots, furthermore if you investigate screenshots you'll find out this happens only if the javascript(browser) version is enabled (I don't think the issue is caused by browser) 

No issue with PCRE:
![2021-06-25_12:46:09_scr](https://user-images.githubusercontent.com/11356471/123393854-c1aaf180-d5b3-11eb-9594-74bd9171ae87.png)

Not working as Expected in global setting:
![2021-06-25_12:46:26_scr](https://user-images.githubusercontent.com/11356471/123393855-c2dc1e80-d5b3-11eb-888a-d2ef32c9ce4e.png)

No issue when multiline enabled:
![2021-06-25_12:46:47_scr](https://user-images.githubusercontent.com/11356471/123393859-c40d4b80-d5b3-11eb-87a3-30b7ed817515.png)

**Comment by wdamien** [comment]
This is actually working as expected. You have a newline as the last character, since it's not a word character JS won't match it.

PCRE is working because the default behavior of $ is to ignore the final character if it's a single newline.  For more details check the "D" modifier docs here: https://www.php.net/manual/en/reference.pcre.pattern.modifiers.php#:~:text=d%20(pcre_dollar_endonly)

**Comment by parsa-ra** [comment]
Got it thanks
