### ISSUE TITLE
Convert Regex value to its string contain

### ISSUE THREAD

**Issue by DavidAbou** [gskinner/regexr#484]
JAVASCRIPT : Hello everyone ! Does it exist, a function that, from a regex /[A-Z]/ return a string that contain all possible match, so "ABCDEFGHIJKLMNOPQRSTUVWXYZ" ? Sorry for my english...

**Comment by giancarloliver** [comment]
rer

**Comment by seppestas** [comment]
This issue tracker is for regexr, a tool to test regexes. This is a general question regarding programming related to regexes. This question might be better suited for one of the [stack exchange](https://stackexchange.com/) sites like [Stack overflow](https://stackoverflow.com/). Be sure to mention what programming language you want to use.

I suggest closing this issue because it is off-topic.

In an attempt to be of help anyway:

Short answer is no. What you are looking for is verry specific and regexes are generic. Your example is a lot simpler than most regexes, imagine what it would happen for more generic regex like \`.*\`. It's set of matched result is infinitely large because the string can be infinitely long!

For your example, assuming you are only interested in ASCII and not e.g Unicode, a quick and dirty for loop could do that for you:

E.g (in JS):

```javascript
const re = /[A-Z]/;
result = '';
for (test = 'A'; test.charCodeAt(0) < 'Z'.charCodeAt(0); test = String.fromCharCode(test.charCodeAt(0) + 1)) {
	match = test.match(re);
  if (match) {
  	console.log(match);
    result += match;
  }
}
console.log(result);
```

This works because each character has it's own numerical code: https://en.wikipedia.org/wiki/ASCII#Printable_characters.
