### ISSUE TITLE
Provide a simple share-by-link

### ISSUE THREAD

**Issue by AmitJoki** [gskinner/regexr#53]
I love regexr, but I answer a lot on Stack Overflow and I'm forced to use regex101 as it easily and fastly gives me the link, which I can post in my answer.

The process in regexr.com is very complicated. Can't we have something like what regex101 does when you click save button?

**Comment by RobThree** [comment]
I'm not quite sure how sharing on regexr is *supposed* to work but yesterday [I shared a few links}(http://stackoverflow.com/a/36670532/215042) (3, 4) and later the person asking the question updated his question [with a link too](http://stackoverflow.com/q/36670494/215042). Today it turns out all links are no longer working. This makes the complete StackOverflow question pretty useless (mostly because the person asking the question deleted about everything else in his question, relying on the information staying up on regexr.com I suppose).

Thankfully I had most of what was important incorporated into my answer but it still kinds sucks that all those links somehow seem to have expired(?)... 

Just my $0.02

**Comment by wdamien** [comment]
@RobThree  Rest assured all those links still exist. We never delete (or expire) any saved patterns. That being said, we have recently been experiencing a noticeable server slow down, and in some cases patters don't load at all. We should (and will) beef up this portion of the UI, as currently we just silently fail when patterns don't load (our bad!). We are investigating the performance issues and will hopefully have a solution soon, since yes its a huge inconvenience when saved data won't load.

**Comment by gskinner** [comment]
We're rebuilding save & share in v3.0 to hopefully be a little easier and more intuitive.

**Comment by gskinner** [comment]
v3.0 has a totally revamped save and share model. The quick version:
Hit `ctrl-s`, tap the link row. Bam! It's in your clipboard.

Feel free to reopen with suggestions to improve it.
