### ISSUE TITLE
Empty substitution strings are not saved.

### ISSUE THREAD

**Issue by gskinner** [gskinner/regexr#83]
Empty substitution strings should be saved if the panel is open. Often the whole goal is to strip out the match. See: http://regexr.com/3aeut

**Comment by wdamien** [comment]
Fixed; The empty substitution strings were always saved, the issue was when the substitution panel was closed empty strings were also being saved. So we had no way of knowing if the empty save was intentional or not, and would show the default value in that case. Fixed by added a new state object to the saves.
