### ISSUE TITLE
Please add RTL support

### ISSUE THREAD

**Issue by weitzhandler** [gskinner/regexr#91]
Please add an option to work with right-to-left languages, such as Hebrew, Arabic, Persian etc.

In dual or more enabled PCs, moving between language direction is enabled by pressing <kbd>Left-Ctrl</kbd>+<kbd>Shift</kbd> or <kbd>Right-Ctrl</kbd>+<kbd>Shift</kbd> accordingly.  
Trying those combinations on RegExr won't do anything, please fix that for the content and substitution fields.

Note: Since the pattern fields are all in English (or using unicode), I believe these should be left LTR.

**Comment by gskinner** [comment]
CodeMirror supports RTL, so this may be possible. If it's as simple as toggling RTL in CM, this could be an easy add, but because I'm not literate with any RTL languages, I'm really not sure what else would be required (ex. does it impact the Expression? Execution? Documentation? Tools?).

If someone wants to propose a plan and scope (post v3.0), I'd be happy to review and consider a pull request for this.

**Comment by gskinner** [comment]
Still open to someone working on this, but closing since I don't really have the experience for it.

**Comment by imme-emosol** [comment]
Highlighting mixed rtl & ltr seems to have an issue . For instance https://regexr.com/8g244 , matched group for `http://مثال.إختبار` when given `/^(?:(?:(?:https?|ftp):)?\/\/)(?:(?:[a-z0-9\u00a1-\uffff](?:[a-z0-9\u00a1-\uffff_]|(?<!-)-(?!-)){0,62})?[a-z0-9\u00a1-\uffff]\.)+(?:[a-z\u00a1-\uffff]{2,})?$/gimu` , the matched text in the hover does show the word .
